name: 'Build and push kotsadm image'
description: 'Composite action for building and pushing kotsadm image'
inputs:
  image-name:
    description: 'Full destination kotsadm image name'
    required: true

  git-tag:
    description: 'Git tag'
    required: true

  registry-username:
    description: 'Username to login to registry'
    default: ''
    required: false

  registry-password:
    description: 'Password to login to registry'
    default: ''
    required: false

runs:
  using: "composite"
  steps:
    - uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033 # v1.1.1
      with:
        workload_identity_provider: ${{secrets.CHAINGUARD_GCP_WIF_POOL}}
        service_account: ${{secrets.CHAINGUARD_GCP_SA}}

    - uses: google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b # v1.1.1
      with:
        project_id: ${{secrets.CHAINGUARD_GCP_PROJECT_ID}}

    - name: setup packages gcsfuse
      env:
        BUCKET: replicated-apk-registry
      run: |
        # Set up a gcsfuse RO mount to the bucket containing private packages. This is a cheap and
        # cheerful way to get access to objects we need, without having to fetch all of them.
        mkdir -p /gcsfuse/apk-repo
        gcsfuse -o ro --implicit-dirs --only-dir os ${BUCKET} /gcsfuse/apk-repo

        # Symlink the gcsfuse mount to ./packages/$arch/*.apk
        mkdir -p ./packages/x86_64
        ln -s /gcsfuse/apk-repo/x86_64/*.apk ./packages/x86_64/

        # Make a copy of the APKINDEX.* since we'll need to write to it on package builds
        cp /gcsfuse/apk-repo/x86_64/APKINDEX.* ./packages/x86_64/

        ls -lR ./packages/

    - name: template melange and apko configs
      shell: bash
      run: |
        export GIT_TAG=${{ inputs.git-tag }}
        envsubst '${GIT_TAG}' < deploy/melange.yaml.tmpl > deploy/melange.yaml
        envsubst '${GIT_TAG}' < deploy/apko.yaml.tmpl > deploy/apko.yaml

    - id: cache-dir
      shell: bash
      run: echo "cache_dir=$(go env GOMODCACHE)" >> "$GITHUB_OUTPUT"

    - uses: chainguard-dev/actions/melange-build@main
      with:
        config: deploy/melange.yaml
        archs: x86_64
        sign-with-temporary-key: true
        cache-dir: ${{ steps.cache-dir.outputs.cache_dir }}

    - uses: chainguard-images/actions/apko-publish@main
      with:
        config: deploy/apko.yaml
        archs: x86_64
        tag: ${{ inputs.image-name }}
        vcs-url: true
        generic-user: ${{ inputs.registry-username }}
        generic-pass: ${{ inputs.registry-password }}
