on:
  pull_request:

jobs:
  presubmit-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.x'
      - uses: chainguard-dev/actions/melange-build@main
        with:
          config: melange.yaml
          archs: x86_64
          sign-with-temporary-key: true
      - uses: chainguard-images/actions/apko-publish@main
        with:
          config: apko.yaml
          archs: x86_64
          tag: ttl.sh/kots
          vcs-url: true
